class AppConstants {
  //picture from Nikolas Jeromin from pexels
  static const homeHeaderImage =
      'assets/pexels-njeromin-18981045.jpg';

  static const onboardingBackground =
      'assets/pexels-fwstudio-33348-129733.jpg';
  //generated by canva ai, thanks! canva Ai lmao ;)
  static const onboardingImage = 'picheaven_logo.png';
}
