class AppConstants {
  //picture from fwstudio from pexels
  static const homeHeaderImage =
      'assets/assets/pexels-fwstudio-33348-129733.jpg';

  static const onboardingBackground =
      'assets/assets/pexels-fwstudio-33348-129733.jpg';
  //generated by canva ai, thanks! canva Ai lmao ;)
  static const onboardingImage = 'picheaven_logo.png';
}
